# Generated by Django 5.0.6 on 2024-06-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantily',
            new_name='quantity',
        ),
    ]
